title: A Level Notes
description: Your A Level study companion

permalink: pretty

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    line_numbers: true
  auto_ids: true
  toc_levels: 1..6

# Collections
collections:
  subjects:
    output: true
    permalink: /notes/:path/
  business:
    output: true
    permalink: /notes/business/:path/
  mathematics:
    output: true
    permalink: /notes/mathematics/:path/
  computer_science:
    output: true
    permalink: /notes/computer_science/:path/
  test_subjects: # Test collections from here
    output: true
    permalink: /tests/:path/
  business_test:
    output: true
    permalink: /tests/business/:path/
  mathematics_test:
    output: true
    permalink: /tests/mathematics/:path/
  computer_science_test:
    output: true
    permalink: /tests/computer_science/:path/

include:
  - _business
  - _computer_science
  - _mathematics